service: tinyurlz


provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  stage: prod
  environment:
    NODE_ENV: ${env:NODE_ENV}
    MONGO_URI: ${env:MONGO_URI}
    ORIGIN: ${env:ORIGIN}
    JWT_SECRET: ${env:JWT_SECRET}
    JWT_EXPIRATION: ${env:JWT_EXPIRATION}
    APP_URL: ${env:APP_URL}
    GOOGLE_CLIENT_ID: ${env:GOOGLE_CLIENT_ID}
  timeout: 10
  apiGateway:
    binaryMediaTypes:
      - "*/*"

functions:
  app:
    handler: handler.handler
    events:
      - http:
          path: /{proxy+}
          method: any
          cors:
            origin: ${env:ORIGIN}
            headers:
              - Content-Type
              - Authorization
              - X-Requested-With
              - Origin
              - Accept
            allowCredentials: true
plugins:
  - serverless-offline

package:
  exclude:
    - .gitignore
    - README.md
  include:
    - node_modules/**
